# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(282826)
$foreground = rgb(DEDFCA)
$color0 = rgb(4D4D4B)
$color1 = rgb(1E1E17)
$color2 = rgb(24241B)
$color3 = rgb(3D5025)
$color4 = rgb(4C4C32)
$color5 = rgb(74744A)
$color6 = rgb(797A4D)
$color7 = rgb(C8C9AB)
$color8 = rgb(8C8C77)
$color9 = rgb(28281F)
$color10 = rgb(303023)
$color11 = rgb(516B32)
$color12 = rgb(656643)
$color13 = rgb(9A9B62)
$color14 = rgb(A2A367)
$color15 = rgb(C8C9AB)
