# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# This is where you put your own keybinds. Be Mindful to check as well ~/.config/hypr/configs/Keybinds.conf to avoid conflict
# if you think I should replace the Pre-defined Keybinds in ~/.config/hypr/configs/Keybinds.conf , submit an issue or let me know in DC and present me a valid reason as to why, such as conflicting with global shortcuts, etc etc

# See https://wiki.hyprland.org/Configuring/Keywords/ for more settings and variables
# See also Laptops.conf for laptops keybinds 

# /* ---- ✴️ Variables ✴️ ---- */  #
$mainMod = SUPER
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts
$UserConfigs = $HOME/.config/hypr/UserConfigs

# Launch Gemini CLI as a Copilot pop-up
bindd = $mainMod SHIFT, C, Gemini Copilot, exec, $scriptsDir/ToggleApp.sh gemini "kitty --title Gemini-Copilot gemini" Gemini-Copilot

# Launch btop as a system monitor pop-up
bindd = CTRL SHIFT, Escape, System Monitor, exec, $scriptsDir/ToggleApp.sh btop "kitty --title btop-float btop" btop-float
