# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DEDFCA
background         #282826
cursor             #878777

active_tab_foreground     #282826
active_tab_background     #DEDFCA
inactive_tab_foreground   #DEDFCA
inactive_tab_background   #282826

active_border_color   #DEDFCA
inactive_border_color #282826
bell_border_color     #1E1E17

color0      #4D4D4B
color1		#1E1E17
color2		#24241B
color3		#3D5025
color4		#4C4C32
color5		#74744A
color6		#797A4D
color7		#C8C9AB
color8		#8C8C77
color9		#28281F
color10		#303023
color11		#516B32
color12		#656643
color13		#9A9B62
color14		#A2A367
color15		#C8C9AB
